source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'liquid', '~> 2.6.1'
gem 'sqlite3-ruby', '~> 1.3.3'
gem 'rspec', '~> 3.0.0'
gem 'posix-spawn', '~> 0.3.8'
gem 'rest-client', '~> 1.7.2'
gem 'toml', '~> 0.1.1'
gem 'escape_utils', '~> 1.0.1'